id: BitcoinAbuse-test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: BitcoinAbuse-test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: de08589e-6d0f-4b33-8f72-2d019f50bff2
    type: start
    task:
      id: de08589e-6d0f-4b33-8f72-2d019f50bff2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: [ ]
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 6739a4e6-dc65-4b25-8e4d-1bebc79725ab
    type: regular
    task:
      id: 6739a4e6-dc65-4b25-8e4d-1bebc79725ab
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: { }
      key: { }
      keysToKeep: { }
      subplaybook: { }
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: [ ]
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 0de2b8ac-56be-49c8-84b0-08501399e120
    type: regular
    task:
      id: 0de2b8ac-56be-49c8-84b0-08501399e120
      version: -1
      name: Bitcoin Report Address
      description: Reports an abuser to Bitcoin Abuse service. 'abuse_type_other' field is
        required when 'abuse_type' is other
      script: '|||bitcoin-report-address'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
        - "3"
    scriptarguments:
      abuse_type:
        simple: bitcoin tumbler
      abuse_type_other: { }
      abuser:
        simple: abuser@abuse.net
      address:
        simple: L1eqWYHYFrcMfFP4Ckn7tT9UnNeCyhssnfw6RaKYxPZgwNQy1neK
      description:
        simple: this is a description of the abuse
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: [ ]
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: e46db6bf-349c-456e-82f8-822bafe0833d
    type: regular
    task:
      id: e46db6bf-349c-456e-82f8-822bafe0833d
      version: -1
      name: Bitcoin Fetch Indicators
      description: fetches indicators from BitcoinAbuse API
      script: BitcoinAbuse|||fetch-indicators
      type: regular
      iscommand: true
      brand: BitcoinAbuse
    nexttasks:
      '#none#':
        - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: [ ]
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: e0f26460-51d7-42ed-861d-e63cb81479dd
    type: title
    task:
      id: e0f26460-51d7-42ed-861d-e63cb81479dd
      version: -1
      name: Playbook Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: [ ]
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: [ ]
outputs: [ ]
fromversion: 5.5.0